[lib]
proc-macro = true

[package]
name = "shared-macros"
version.workspace = true
edition.workspace = true

[dependencies]
quote.workspace = true
syn.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }
