[package]
name = "sdk-py"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sdk_py"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
sdk-core.workspace = true
sdk-proto.workspace = true
tokio.workspace = true
tonic.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
shared.workspace = true
