
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "sdk-js"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "3", features = ["serde-json", "tokio_rt", "async"]}
napi-derive = "3.0.0"
once_cell = "1.20"
sdk-core.workspace = true
sdk-proto.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
shared.workspace = true

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
