[package]
name = "soma"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "soma"
path = "src/main.rs"

[dependencies]
a2a-rs.workspace = true
anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
chrono.workspace = true
clap.workspace = true
http.workspace = true
humantime.workspace = true
libsql.workspace = true
restate-admin-rest-model.workspace = true
restate-serde-util.workspace = true
restate-types.workspace = true
rmcp.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
shared.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-graceful-shutdown.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
utoipa-axum.workspace = true
uuid.workspace = true
vite-rs.workspace = true
vite-rs-axum-0-8.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }
async-trait.workspace = true
futures.workspace = true
dashmap = "6.1.0"
notify = "8.2.0"
globset = "0.4.16"
notify-debouncer-full = "0.6.0"
tokio-stream.workspace = true
tokio-util = "0.7.16"
schemars.workspace = true
restate-sdk = "0.7.0"
urlencoding = "2.1.3"
base64.workspace = true
